from pyamaze import maze,agent
m=maze()
m.CreateMaze(5,5,loadMaze="maze4.csv")
a=agent(m,filled=True)
a.position=(8,8)
a.footprints=(True)
m.tracePath({a:m.path})
#m=maze()
#m.CreateMaze(2,2,loadMaze="maze1.csv")
m.run()
